#!/usr/bin/env python3
"""QuantAgent autonomous dev orchestrator (v1: design generation).

Responsibilities (v1):
- Read ready issues from `bd ready --json`
- For each issue, generate a design doc (via OpenClaw skills - stubbed for now)
- Commit the design doc to a shared branch
- Move the issue to a "design pending" gate in bd (blocked + label)

This is intentionally conservative and idempotent.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
OPENCLAW_DIR = REPO_ROOT / "openclaw"
STATE_DIR = OPENCLAW_DIR / "state"
LOG_DIR = OPENCLAW_DIR / "logs"
DESIGN_DIR = REPO_ROOT / "docs" / "design"
DEFAULT_EPIC_BRANCH = "epic/openclaw-dev"

PENDING_LABEL = "openclaw:design_pending"
APPROVED_LABEL = "openclaw:design_approved"


@dataclass
class BdIssue:
    id: str
    title: str
    description: str | None
    status: str | None
    priority: int | None
    issue_type: str | None
    labels: list[str]
    metadata: dict[str, Any] | None = None


def sh(cmd: list[str], *, cwd: Path | None = None, check: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, cwd=cwd, check=check, text=True, capture_output=True)


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def bd_json(cmd: list[str]) -> Any:
    p = sh(["bd", *cmd, "--json"], cwd=REPO_ROOT)
    try:
        return json.loads(p.stdout)
    except json.JSONDecodeError as e:
        raise RuntimeError(f"Failed parsing bd JSON for cmd={cmd}: {e}; stdout={p.stdout[:500]}")


def git(*args: str) -> str:
    p = sh(["git", *args], cwd=REPO_ROOT)
    return p.stdout.strip()


def ensure_branch(branch: str) -> None:
    # Create branch off main if it doesn't exist locally.
    branches = git("branch", "--list", branch)
    if branches.strip():
        return
    git("fetch", "origin", "main")
    git("checkout", "-b", branch, "origin/main")


def checkout(branch: str) -> None:
    git("checkout", branch)


def write_design_doc(issue: BdIssue) -> Path:
    DESIGN_DIR.mkdir(parents=True, exist_ok=True)
    path = DESIGN_DIR / f"{issue.id}-design.md"

    content = (
        f"# Design: {issue.title}\n"
        f"Issue: {issue.id}\n"
        f"Generated: {now_iso()}\n\n"
        "## Summary\n"
        "(v1 placeholder)\n\n"
        "## Ticket Context\n"
        f"{issue.description or ''}\n\n"
        "## Proposed Changes\n"
        "- TBD (generated by design-generator skill in v2)\n"
    )

    path.write_text(content, encoding="utf-8")
    return path


def commit_file(path: Path, issue_id: str) -> None:
    git("add", str(path.relative_to(REPO_ROOT)))
    # Commit only if staged changes exist
    if not git("diff", "--cached", "--name-only"):
        return
    git("commit", "-m", f"[{issue_id}] Add design document")


def bd_update(issue_id: str, *, status: str | None = None, add_labels: list[str] | None = None, metadata: dict[str, Any] | None = None) -> None:
    cmd = ["update", issue_id]
    if status is not None:
        cmd += ["--status", status]
    if add_labels:
        for l in add_labels:
            cmd += ["--add-label", l]
    if metadata is not None:
        cmd += ["--metadata", json.dumps(metadata)]
    sh(["bd", *cmd], cwd=REPO_ROOT)


def issue_from_obj(o: dict[str, Any]) -> BdIssue:
    return BdIssue(
        id=o["id"],
        title=o.get("title", ""),
        description=o.get("description"),
        status=o.get("status"),
        priority=o.get("priority"),
        issue_type=o.get("issue_type"),
        labels=o.get("labels") or [],
        metadata=o.get("metadata"),
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--limit", type=int, default=3)
    ap.add_argument("--epic-branch", default=DEFAULT_EPIC_BRANCH)
    args = ap.parse_args()

    STATE_DIR.mkdir(parents=True, exist_ok=True)
    LOG_DIR.mkdir(parents=True, exist_ok=True)

    ready = bd_json(["ready", "--limit", str(args.limit)])
    issues = [issue_from_obj(x) for x in ready]

    if not issues:
        print("No ready issues.")
        return 0

    ensure_branch(args.epic_branch)
    checkout(args.epic_branch)

    processed = 0
    for issue in issues:
        # Idempotency: if it's already labeled pending, skip.
        if PENDING_LABEL in issue.labels:
            continue

        design_path = write_design_doc(issue)
        commit_file(design_path, issue.id)

        md = {
            "openclaw": {
                "phase": "design_pending",
                "design_doc_path": str(design_path.relative_to(REPO_ROOT)),
                "design_branch": args.epic_branch,
                "updated_at": now_iso(),
            }
        }

        bd_update(issue.id, status="blocked", add_labels=[PENDING_LABEL], metadata=md)
        processed += 1

    print(json.dumps({"processed": processed, "branch": args.epic_branch}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
