"""Fix JSON index on backtest_runs- remove btree index

Revision ID: 1543e9a20a69
Revises: 89b89b8ee086
Create Date: 2025-11-27 00:28:42.985847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1543e9a20a69'
down_revision: Union[str, Sequence[str], None] = '89b89b8ee086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('filled_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_orders_filled_at'), 'orders', ['filled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_filled_at'), table_name='orders')
    op.drop_column('orders', 'filled_at')
    # ### end Alembic commands ###
