"""Add environment tagging,  provenance, checkpoint metadata, and new StrategyConfig/BacktestRun models

Revision ID: 3a79614a69d2
Revises: 830b128fd5df
Create Date: 2025-11-26 22:14:16.758598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '3a79614a69d2'
down_revision: Union[str, Sequence[str], None] = '830b128fd5df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create ENUM type first
    environment_enum = postgresql.ENUM('BACKTEST', 'PAPER', 'PROD', name='environment')
    environment_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('assets', sa.JSON(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('data_source', sa.String(length=200), nullable=True),
    sa.Column('config_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('total_pnl', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_start_end_date', 'backtest_runs', ['start_date', 'end_date'], unique=False)
    op.create_index(op.f('ix_backtest_runs_created_at'), 'backtest_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_backtest_runs_end_date'), 'backtest_runs', ['end_date'], unique=False)
    op.create_index(op.f('ix_backtest_runs_start_date'), 'backtest_runs', ['start_date'], unique=False)
    op.create_table('strategy_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('json_config', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_name_kind', 'strategy_configs', ['name', 'kind'], unique=False)
    op.create_index(op.f('ix_strategy_configs_created_at'), 'strategy_configs', ['created_at'], unique=False)
    op.create_index(op.f('ix_strategy_configs_id'), 'strategy_configs', ['id'], unique=False)
    op.create_index(op.f('ix_strategy_configs_name'), 'strategy_configs', ['name'], unique=True)
    op.add_column('orders', sa.Column('environment', sa.Enum('BACKTEST', 'PAPER', 'PROD', name='environment'), nullable=False, server_default='PAPER'))
    op.add_column('orders', sa.Column('trigger_signal_id', sa.Integer(), nullable=True))
    op.create_index('idx_orders_environment', 'orders', ['environment'], unique=False)
    op.create_foreign_key(None, 'orders', 'signals', ['trigger_signal_id'], ['id'])
    op.add_column('signals', sa.Column('environment', sa.Enum('BACKTEST', 'PAPER', 'PROD', name='environment'), nullable=False, server_default='PAPER'))
    op.add_column('signals', sa.Column('order_id', sa.Integer(), nullable=True))
    op.add_column('signals', sa.Column('thread_id', sa.String(length=100), nullable=True))
    op.add_column('signals', sa.Column('checkpoint_id', sa.String(length=100), nullable=True))
    op.add_column('signals', sa.Column('state_snapshot', sa.JSON(), nullable=True))
    op.add_column('signals', sa.Column('model_provider', sa.String(length=50), nullable=True))
    op.add_column('signals', sa.Column('model_name', sa.String(length=100), nullable=True))
    op.add_column('signals', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('signals', sa.Column('agent_version', sa.String(length=50), nullable=True))
    op.add_column('signals', sa.Column('graph_version', sa.String(length=50), nullable=True))
    op.create_index('idx_signals_environment', 'signals', ['environment'], unique=False)
    op.create_index('idx_signals_thread_id', 'signals', ['thread_id'], unique=False)
    op.create_foreign_key(None, 'signals', 'orders', ['order_id'], ['id'])
    op.add_column('trades', sa.Column('environment', sa.Enum('BACKTEST', 'PAPER', 'PROD', name='environment'), nullable=False, server_default='PAPER'))
    op.create_index('idx_trades_environment', 'trades', ['environment'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_trades_environment', table_name='trades')
    op.drop_column('trades', 'environment')
    op.drop_constraint(None, 'signals', type_='foreignkey')
    op.drop_index('idx_signals_thread_id', table_name='signals')
    op.drop_index('idx_signals_environment', table_name='signals')
    op.drop_column('signals', 'graph_version')
    op.drop_column('signals', 'agent_version')
    op.drop_column('signals', 'temperature')
    op.drop_column('signals', 'model_name')
    op.drop_column('signals', 'model_provider')
    op.drop_column('signals', 'state_snapshot')
    op.drop_column('signals', 'checkpoint_id')
    op.drop_column('signals', 'thread_id')
    op.drop_column('signals', 'order_id')
    op.drop_column('signals', 'environment')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index('idx_orders_environment', table_name='orders')
    op.drop_column('orders', 'trigger_signal_id')
    op.drop_column('orders', 'environment')
    op.drop_index(op.f('ix_strategy_configs_name'), table_name='strategy_configs')
    op.drop_index(op.f('ix_strategy_configs_id'), table_name='strategy_configs')
    op.drop_index(op.f('ix_strategy_configs_created_at'), table_name='strategy_configs')
    op.drop_index('idx_name_kind', table_name='strategy_configs')
    op.drop_table('strategy_configs')
    op.drop_index(op.f('ix_backtest_runs_start_date'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_end_date'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_created_at'), table_name='backtest_runs')
    op.drop_index('idx_start_end_date', table_name='backtest_runs')
    op.drop_table('backtest_runs')
    # ### end Alembic commands ###

    # Drop ENUM type at the end
    environment_enum = postgresql.ENUM('BACKTEST', 'PAPER', 'PROD', name='environment')
    environment_enum.drop(op.get_bind(), checkfirst=True)
