"""Add logs table for structured logging

Revision ID: 6f9b34635f4b
Revises: bc62fb14351d
Create Date: 2026-01-10 02:41:50.462457

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f9b34635f4b"
down_revision: Union[str, Sequence[str], None] = "bc62fb14351d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("level", sa.String(length=10), nullable=False),
        sa.Column("module", sa.String(length=100), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("environment", sa.String(length=20), nullable=True),
        sa.Column("symbol", sa.String(length=20), nullable=True),
        sa.Column("event_type", sa.String(length=50), nullable=True),
        sa.Column("extra_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("thread_id", sa.String(length=100), nullable=True),
        sa.Column("checkpoint_id", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_logs_environment"), "logs", ["environment"], unique=False)
    op.create_index(op.f("ix_logs_event_type"), "logs", ["event_type"], unique=False)
    op.create_index(op.f("ix_logs_level"), "logs", ["level"], unique=False)
    op.create_index(op.f("ix_logs_symbol"), "logs", ["symbol"], unique=False)
    op.create_index(op.f("ix_logs_thread_id"), "logs", ["thread_id"], unique=False)
    op.create_index(op.f("ix_logs_timestamp"), "logs", ["timestamp"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_logs_timestamp"), table_name="logs")
    op.drop_index(op.f("ix_logs_thread_id"), table_name="logs")
    op.drop_index(op.f("ix_logs_symbol"), table_name="logs")
    op.drop_index(op.f("ix_logs_level"), table_name="logs")
    op.drop_index(op.f("ix_logs_event_type"), table_name="logs")
    op.drop_index(op.f("ix_logs_environment"), table_name="logs")
    op.drop_table("logs")
    # ### end Alembic commands ###
