"""Create initial schema
   with Order, Fill, Position, Signal, Trade, MarketData tables

Revision ID: 830b128fd5df
Revises: 
Create Date: 2025-11-25 15:50:33.140911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '830b128fd5df'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_symbol_timeframe_timestamp', 'market_data', ['symbol', 'timeframe', 'timestamp'], unique=False)
    op.create_index('idx_timestamp', 'market_data', ['timestamp'], unique=False)
    op.create_index(op.f('ix_market_data_id'), 'market_data', ['id'], unique=False)
    op.create_index(op.f('ix_market_data_symbol'), 'market_data', ['symbol'], unique=False)
    op.create_index(op.f('ix_market_data_timestamp'), 'market_data', ['timestamp'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='orderside'), nullable=False),
    sa.Column('order_type', sa.Enum('MARKET', 'LIMIT', 'STOP', 'STOP_LIMIT', name='ordertype'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'FILLED', 'PARTIALLY_FILLED', 'CANCELLED', 'REJECTED', name='orderstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('filled_quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('average_fill_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_status_symbol', 'orders', ['status', 'symbol'], unique=False)
    op.create_index('idx_symbol_created_at', 'orders', ['symbol', 'created_at'], unique=False)
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_symbol'), 'orders', ['symbol'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('average_entry_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('unrealized_pnl_pct', sa.Float(), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='orderside'), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_id'), 'positions', ['id'], unique=False)
    op.create_index(op.f('ix_positions_opened_at'), 'positions', ['opened_at'], unique=False)
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=True)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('signal', sa.Enum('LONG', 'SHORT', 'NEUTRAL', 'CLOSE', name='tradesignal'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('rsi', sa.Float(), nullable=True),
    sa.Column('macd', sa.Float(), nullable=True),
    sa.Column('stochastic', sa.Float(), nullable=True),
    sa.Column('roc', sa.Float(), nullable=True),
    sa.Column('williams_r', sa.Float(), nullable=True),
    sa.Column('pattern', sa.String(length=100), nullable=True),
    sa.Column('trend', sa.String(length=50), nullable=True),
    sa.Column('analysis_summary', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_symbol_generated_at', 'signals', ['symbol', 'generated_at'], unique=False)
    op.create_index('idx_symbol_signal', 'signals', ['symbol', 'signal'], unique=False)
    op.create_index(op.f('ix_signals_generated_at'), 'signals', ['generated_at'], unique=False)
    op.create_index(op.f('ix_signals_id'), 'signals', ['id'], unique=False)
    op.create_index(op.f('ix_signals_symbol'), 'signals', ['symbol'], unique=False)
    op.create_table('fills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('commission', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('filled_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_order_filled_at', 'fills', ['order_id', 'filled_at'], unique=False)
    op.create_index(op.f('ix_fills_filled_at'), 'fills', ['filled_at'], unique=False)
    op.create_index(op.f('ix_fills_id'), 'fills', ['id'], unique=False)
    op.create_index(op.f('ix_fills_order_id'), 'fills', ['order_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='orderside'), nullable=False),
    sa.Column('pnl', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('commission', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('entry_signal', sa.String(length=50), nullable=True),
    sa.Column('exit_signal', sa.String(length=50), nullable=True),
    sa.Column('timeframe', sa.String(length=10), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_symbol_closed_at', 'trades', ['symbol', 'closed_at'], unique=False)
    op.create_index('idx_symbol_opened_at', 'trades', ['symbol', 'opened_at'], unique=False)
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    op.create_index(op.f('ix_trades_opened_at'), 'trades', ['opened_at'], unique=False)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index(op.f('ix_trades_opened_at'), table_name='trades')
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_index('idx_symbol_opened_at', table_name='trades')
    op.drop_index('idx_symbol_closed_at', table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_fills_order_id'), table_name='fills')
    op.drop_index(op.f('ix_fills_id'), table_name='fills')
    op.drop_index(op.f('ix_fills_filled_at'), table_name='fills')
    op.drop_index('idx_order_filled_at', table_name='fills')
    op.drop_table('fills')
    op.drop_index(op.f('ix_signals_symbol'), table_name='signals')
    op.drop_index(op.f('ix_signals_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_generated_at'), table_name='signals')
    op.drop_index('idx_symbol_signal', table_name='signals')
    op.drop_index('idx_symbol_generated_at', table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_index(op.f('ix_positions_opened_at'), table_name='positions')
    op.drop_index(op.f('ix_positions_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_orders_symbol'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_index('idx_symbol_created_at', table_name='orders')
    op.drop_index('idx_status_symbol', table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_market_data_timestamp'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_symbol'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_id'), table_name='market_data')
    op.drop_index('idx_timestamp', table_name='market_data')
    op.drop_index('idx_symbol_timeframe_timestamp', table_name='market_data')
    op.drop_table('market_data')
    # ### end Alembic commands ###
