"""Add trading components schema

Revision ID: 89b89b8ee086
Revises: 3a79614a69d2
Create Date: 2025-11-26 23:31:11.455889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89b89b8ee086'
down_revision: Union[str, Sequence[str], None] = '3a79614a69d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: Removed idx_assets on JSON column (PostgreSQL doesn't support BTREE on JSON)
    # For MVP, we don't need to index JSON columns
    op.create_index(op.f('ix_backtest_runs_id'), 'backtest_runs', ['id'], unique=False)
    op.create_index(op.f('ix_orders_environment'), 'orders', ['environment'], unique=False)
    op.create_index(op.f('ix_signals_environment'), 'signals', ['environment'], unique=False)
    op.create_index(op.f('ix_trades_environment'), 'trades', ['environment'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_environment'), table_name='trades')
    op.drop_index(op.f('ix_signals_environment'), table_name='signals')
    op.drop_index(op.f('ix_orders_environment'), table_name='orders')
    op.drop_index(op.f('ix_backtest_runs_id'), table_name='backtest_runs')
    # NOTE: Removed idx_assets (was on JSON column, not supported)
    # ### end Alembic commands ###
