"""add_active_positions_table

Revision ID: f7d3bad02cae
Revises: bc62fb14351d
Create Date: 2026-01-10 02:09:53.812633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f7d3bad02cae'
down_revision: Union[str, Sequence[str], None] = 'bc62fb14351d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='orderside'), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('take_profit', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('decision_timestamp', sa.DateTime(), nullable=False),
    sa.Column('candles_since_entry', sa.Integer(), nullable=False),
    sa.Column('exit_policy', sa.Enum('SL_TP_ONLY', 'TIME_BASED', 'REEVALUATE', 'TRAILING_STOP', name='exitpolicy'), nullable=False),
    sa.Column('max_hold_candles', sa.Integer(), nullable=True),
    sa.Column('prediction_horizon', sa.Integer(), nullable=False),
    sa.Column('candles_direction', sa.JSON(), nullable=False),
    sa.Column('trailing_stop_pct', sa.Float(), nullable=True),
    sa.Column('highest_price_seen', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('lowest_price_seen', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('close_reason', sa.String(length=50), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('environment', sa.Enum('BACKTEST', 'PAPER', 'PROD', name='environment'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_active_positions_environment', 'active_positions', ['environment'], unique=False)
    op.create_index('idx_symbol_is_active', 'active_positions', ['symbol', 'is_active'], unique=False)
    op.create_index(op.f('ix_active_positions_decision_timestamp'), 'active_positions', ['decision_timestamp'], unique=False)
    op.create_index(op.f('ix_active_positions_environment'), 'active_positions', ['environment'], unique=False)
    op.create_index(op.f('ix_active_positions_id'), 'active_positions', ['id'], unique=False)
    op.create_index(op.f('ix_active_positions_is_active'), 'active_positions', ['is_active'], unique=False)
    op.create_index(op.f('ix_active_positions_symbol'), 'active_positions', ['symbol'], unique=False)
    # NOTE: Alembic detected checkpoint tables for removal but they're managed by LangGraph
    # op.drop_index(op.f('checkpoints_thread_id_idx'), table_name='checkpoints')
    # op.drop_table('checkpoints')
    # op.drop_table('checkpoint_migrations')
    # op.drop_index(op.f('checkpoint_writes_thread_id_idx'), table_name='checkpoint_writes')
    # op.drop_table('checkpoint_writes')
    # op.drop_index(op.f('checkpoint_blobs_thread_id_idx'), table_name='checkpoint_blobs')
    # op.drop_table('checkpoint_blobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: Checkpoint tables are managed by LangGraph, not recreated here
    # op.create_table('checkpoint_blobs', ...)
    # op.create_table('checkpoint_writes', ...)
    # op.create_table('checkpoint_migrations', ...)
    # op.create_table('checkpoints', ...)
    op.drop_index(op.f('ix_active_positions_symbol'), table_name='active_positions')
    op.drop_index(op.f('ix_active_positions_is_active'), table_name='active_positions')
    op.drop_index(op.f('ix_active_positions_id'), table_name='active_positions')
    op.drop_index(op.f('ix_active_positions_environment'), table_name='active_positions')
    op.drop_index(op.f('ix_active_positions_decision_timestamp'), table_name='active_positions')
    op.drop_index('idx_symbol_is_active', table_name='active_positions')
    op.drop_index('idx_active_positions_environment', table_name='active_positions')
    op.drop_table('active_positions')
    # ### end Alembic commands ###
